### ISSUE TITLE
As a user I want to be able to link my socail media accounts to better showcase myself

### ISSUE THREAD

**Issue by mcke0368** [mcke0368/CST8334#7]
* Have a button that the user can click on their profile that links to their twitter, instagram and facebook
* Add filed in profile creation for social media integration
* Buttons on profile look good and function correctly. Profile integration is seamless.
* Peer review by at least 2 ppl (Not yourself) and merged in successfully.

**Comment by mcke0368** [comment]
/100

**Comment by BunnyJojo** [comment]
I added in hyperlinks to the icons and store the links in the database Video table.
